#!/usr/bin/env bash
#
# Redis Enterprise Installation and Cluster Setup Script
# Generated by terraform-aws-redis-enterprise module
#
set -euo pipefail

# =============================================================================
# Configuration from Terraform template variables
# =============================================================================
SSH_USER="${ssh_user}"
REDIS_DISTRO="${redis_download_url}"
REDIS_ADMIN_USER="${redis_admin_user}"
REDIS_ADMIN_PASSWORD="${redis_admin_password}"
CLUSTER_FQDN="${cluster_fqdn}"
FLASH_ENABLED="${flash_enabled}"
NODE_INDEX="${node_index}"
IS_MASTER="${is_master}"
MASTER_IP="${master_ip}"
RACK_ID="${rack_id}"

LOG_FILE="/home/$${SSH_USER}/install_redis.log"
INSTALL_DIR="/home/$${SSH_USER}/install"

log() {
    echo "$(date -Is) - $1" | tee -a "$LOG_FILE"
}

# =============================================================================
# Detect user if not set properly
# =============================================================================
if [ ! -d "/home/$${SSH_USER}" ]; then
    if [ -d /home/ubuntu ]; then
        SSH_USER=ubuntu
    fi
    LOG_FILE="/home/$${SSH_USER}/install_redis.log"
fi

log "=== Starting Redis Enterprise installation (Node $${NODE_INDEX}) ==="

# =============================================================================
# System Preparation
# =============================================================================
export DEBIAN_FRONTEND=noninteractive
export NEEDRESTART_MODE=a

# Disable needrestart prompts (Ubuntu 22.04+)
if [ -d /etc/needrestart/conf.d ]; then
    cat > /etc/needrestart/conf.d/99-disable-interactive.conf << 'EOF'
$nrconf{restart} = 'a';
$nrconf{kernelhints} = 0;
EOF
fi

# Note: We don't wait for cloud-init here since this script IS running as part of cloud-init (user_data)
# Waiting would cause a deadlock

log "Updating packages..."
apt-get update -y >> /home/$${SSH_USER}/apt.log 2>&1
apt-get upgrade -y >> /home/$${SSH_USER}/apt.log 2>&1
apt-get install -y vim iputils-ping curl jq netcat-openbsd dnsutils wget >> /home/$${SSH_USER}/apt.log 2>&1

# Configure DNS for Redis Enterprise
log "Configuring DNS..."
if ! grep -q "DNSStubListener=no" /etc/systemd/resolved.conf; then
    echo 'DNSStubListener=no' >> /etc/systemd/resolved.conf
fi
if [ -f /etc/resolv.conf ] && [ ! -L /etc/resolv.conf ]; then
    mv /etc/resolv.conf /etc/resolv.conf.orig
    ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf
fi
systemctl restart systemd-resolved

# Configure sysctl
log "Configuring sysctl..."
if ! grep -q "net.ipv4.ip_local_port_range" /etc/sysctl.conf; then
    echo 'net.ipv4.ip_local_port_range = 30000 65535' >> /etc/sysctl.conf
fi
sysctl -w net.ipv4.ip_local_port_range="30000 65535"

# Create rc.local for Ubuntu 22.04+ compatibility
if [ ! -f /etc/rc.local ]; then
    echo -e '#!/bin/bash\nexit 0' > /etc/rc.local
    chmod +x /etc/rc.local
fi

# =============================================================================
# Download and Install Redis Enterprise
# =============================================================================
mkdir -p "$${INSTALL_DIR}"
chown "$${SSH_USER}:$${SSH_USER}" "$${INSTALL_DIR}"
cd "$${INSTALL_DIR}"

log "Downloading Redis Enterprise..."
wget -q "$${REDIS_DISTRO}" -P "$${INSTALL_DIR}"

log "Extracting Redis Enterprise..."
tar xf "$${INSTALL_DIR}"/redislabs*.tar -C "$${INSTALL_DIR}"

log "Installing Redis Enterprise..."
"$${INSTALL_DIR}/install.sh" -y >> /home/$${SSH_USER}/install_rs.log 2>&1

# Add user to redislabs group
adduser "$${SSH_USER}" redislabs 2>/dev/null || true

log "Waiting for services to start..."
sleep 30

# =============================================================================
# Flash Storage Setup (if enabled)
# =============================================================================
if [ "$${FLASH_ENABLED}" = "true" ]; then
    log "Setting up flash storage..."
    if [ -x /opt/redislabs/sbin/prepare_flash.sh ]; then
        /opt/redislabs/sbin/prepare_flash.sh -y 2>&1 | tee -a "$LOG_FILE" || true
    fi
fi

# =============================================================================
# Get Network Info (AWS EC2 Instance Metadata Service v2)
# =============================================================================
# Get IMDSv2 token
TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")

INTERNAL_IP=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/local-ipv4)
EXTERNAL_IP=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || echo "none")

echo "$${INTERNAL_IP} redis-node-$${NODE_INDEX}" >> /etc/hosts

# =============================================================================
# Create or Join Cluster
# =============================================================================
# Export password so rladmin can read it from environment
export RLEC_PASSWORD="$${REDIS_ADMIN_PASSWORD}"

if [ "$${IS_MASTER}" = "true" ]; then
    log "Creating new cluster: $${CLUSTER_FQDN}"

    # Build command with conditional parts
    CMD_OPTS=""
    if [ "$${FLASH_ENABLED}" = "true" ]; then
        CMD_OPTS="$CMD_OPTS flash_enabled"
    fi
    if [ -n "$${RACK_ID}" ]; then
        CMD_OPTS="$CMD_OPTS rack_aware rack_id $${RACK_ID}"
    fi
    if [ "$${EXTERNAL_IP}" != "none" ]; then
        CMD_OPTS="$CMD_OPTS external_addr $${EXTERNAL_IP}"
    fi

    log "Executing: rladmin cluster create name $${CLUSTER_FQDN} username $${REDIS_ADMIN_USER} password *** $CMD_OPTS"
    /opt/redislabs/bin/rladmin cluster create name "$${CLUSTER_FQDN}" username "$${REDIS_ADMIN_USER}" password env:RLEC_PASSWORD $CMD_OPTS 2>&1 | tee -a "$LOG_FILE"
else
    log "Joining cluster at $${MASTER_IP}"
    max_retries=10
    retry_delay=30

    # Build command options
    CMD_OPTS=""
    if [ -n "$${RACK_ID}" ]; then
        CMD_OPTS="$CMD_OPTS rack_id $${RACK_ID}"
    fi
    if [ "$${EXTERNAL_IP}" != "none" ]; then
        CMD_OPTS="$CMD_OPTS external_addr $${EXTERNAL_IP}"
    fi

    for i in $(seq 1 $max_retries); do
        log "Join attempt $i/$max_retries..."
        log "Executing: rladmin cluster join nodes $${MASTER_IP} username $${REDIS_ADMIN_USER} password *** $CMD_OPTS"

        if /opt/redislabs/bin/rladmin cluster join nodes "$${MASTER_IP}" username "$${REDIS_ADMIN_USER}" password env:RLEC_PASSWORD $CMD_OPTS 2>&1 | tee -a "$LOG_FILE"; then
            log "Successfully joined cluster"
            break
        fi

        log "Join failed, retrying in $${retry_delay}s..."
        sleep $retry_delay
    done
fi

# =============================================================================
# Cleanup and Signal Completion
# =============================================================================
rm -f "$${INSTALL_DIR}"/redislabs*.tar

log "=== Redis Enterprise installation complete ==="

# Create marker file to signal cluster is ready
touch /home/$${SSH_USER}/cluster_ready
chown $${SSH_USER}:$${SSH_USER} /home/$${SSH_USER}/cluster_ready

log "Cluster ready marker created"

