#!/usr/bin/env bash
#
# Redis Enterprise Installation and Cluster Setup Script
# Generated by terraform-aws-redis-enterprise module
#
set -euo pipefail

# =============================================================================
# Configuration from Terraform template variables
# =============================================================================
SSH_USER="${ssh_user}"
REDIS_DISTRO="${redis_download_url}"
REDIS_ADMIN_USER="${redis_admin_user}"
REDIS_ADMIN_PASSWORD="${redis_admin_password}"
CLUSTER_FQDN="${cluster_fqdn}"
FLASH_ENABLED="${flash_enabled}"
NODE_INDEX="${node_index}"
IS_MASTER="${is_master}"
MASTER_IP="${master_ip}"
RACK_ID="${rack_id}"
REDIS_LICENSE="${redis_license}"

LOG_FILE="/home/$${SSH_USER}/install_redis.log"
INSTALL_DIR="/home/$${SSH_USER}/install"

log() {
    echo "$(date -Is) - $1" | tee -a "$LOG_FILE"
}

# =============================================================================
# Detect user if not set properly
# =============================================================================
if [ ! -d "/home/$${SSH_USER}" ]; then
    if [ -d /home/ubuntu ]; then
        SSH_USER=ubuntu
    fi
    LOG_FILE="/home/$${SSH_USER}/install_redis.log"
fi

log "=== Starting Redis Enterprise installation (Node $${NODE_INDEX}) ==="

# =============================================================================
# System Preparation
# =============================================================================
export DEBIAN_FRONTEND=noninteractive
export NEEDRESTART_MODE=a

# Disable needrestart prompts (Ubuntu 22.04+)
if [ -d /etc/needrestart/conf.d ]; then
    cat > /etc/needrestart/conf.d/99-disable-interactive.conf << 'EOF'
$nrconf{restart} = 'a';
$nrconf{kernelhints} = 0;
EOF
fi

# Note: We don't wait for cloud-init here since this script IS running as part of cloud-init (user_data)
# Waiting would cause a deadlock

log "Updating packages..."
apt-get update -y >> /home/$${SSH_USER}/apt.log 2>&1
apt-get upgrade -y >> /home/$${SSH_USER}/apt.log 2>&1
apt-get install -y vim iputils-ping curl jq netcat-openbsd dnsutils wget >> /home/$${SSH_USER}/apt.log 2>&1

# Configure DNS for Redis Enterprise
log "Configuring DNS..."
if ! grep -q "DNSStubListener=no" /etc/systemd/resolved.conf; then
    echo 'DNSStubListener=no' >> /etc/systemd/resolved.conf
fi
if [ -f /etc/resolv.conf ] && [ ! -L /etc/resolv.conf ]; then
    mv /etc/resolv.conf /etc/resolv.conf.orig
    ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf
fi
systemctl restart systemd-resolved

# Configure sysctl
log "Configuring sysctl..."
if ! grep -q "net.ipv4.ip_local_port_range" /etc/sysctl.conf; then
    echo 'net.ipv4.ip_local_port_range = 30000 65535' >> /etc/sysctl.conf
fi
sysctl -w net.ipv4.ip_local_port_range="30000 65535"

# Create rc.local for Ubuntu 22.04+ compatibility
if [ ! -f /etc/rc.local ]; then
    echo -e '#!/bin/bash\nexit 0' > /etc/rc.local
    chmod +x /etc/rc.local
fi

# =============================================================================
# Download and Install Redis Enterprise
# =============================================================================
mkdir -p "$${INSTALL_DIR}"
chown "$${SSH_USER}:$${SSH_USER}" "$${INSTALL_DIR}"
cd "$${INSTALL_DIR}"

log "Downloading Redis Enterprise..."
wget -q "$${REDIS_DISTRO}" -P "$${INSTALL_DIR}"

log "Extracting Redis Enterprise..."
tar xf "$${INSTALL_DIR}"/redislabs*.tar -C "$${INSTALL_DIR}"

log "Installing Redis Enterprise..."
"$${INSTALL_DIR}/install.sh" -y >> /home/$${SSH_USER}/install_rs.log 2>&1

# Add user to redislabs group
adduser "$${SSH_USER}" redislabs 2>/dev/null || true

log "Waiting for services to start..."
sleep 30

# =============================================================================
# Flash Storage Setup (if enabled)
# =============================================================================
if [ "$${FLASH_ENABLED}" = "true" ]; then
    log "Setting up flash storage..."
    if [ -x /opt/redislabs/sbin/prepare_flash.sh ]; then
        /opt/redislabs/sbin/prepare_flash.sh -y 2>&1 | tee -a "$LOG_FILE" || true
    fi
fi

# =============================================================================
# Get Network Info (AWS EC2 Instance Metadata Service v2)
# =============================================================================
# Get IMDSv2 token
TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")

INTERNAL_IP=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/local-ipv4)
EXTERNAL_IP=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || echo "none")

echo "$${INTERNAL_IP} redis-node-$${NODE_INDEX}" >> /etc/hosts

# =============================================================================
# Create or Join Cluster using REST API
# =============================================================================
# Note: rladmin has parsing issues in Redis Enterprise 8.x, so we use the REST API instead

# JSON-escape credentials to handle special characters (", \, control chars)
ESCAPED_USERNAME=$(printf '%s' "$${REDIS_ADMIN_USER}" | jq -Rs '.')
ESCAPED_PASSWORD=$(printf '%s' "$${REDIS_ADMIN_PASSWORD}" | jq -Rs '.')

# Build identity object with optional fields
build_identity_json() {
    local parts=()
    if [ "$${EXTERNAL_IP}" != "none" ]; then
        parts+=("\"external_addr\": [\"$${EXTERNAL_IP}\"]")
    fi
    if [ -n "$${RACK_ID}" ]; then
        parts+=("\"rack_id\": \"$${RACK_ID}\"")
    fi
    # Join parts with comma
    local IFS=','
    echo "{$${parts[*]}}"
}

IDENTITY_JSON=$(build_identity_json)

if [ "$${IS_MASTER}" = "true" ]; then
    log "Creating new cluster: $${CLUSTER_FQDN} via REST API"

    # Build cluster object with optional rack_aware
    if [ -n "$${RACK_ID}" ]; then
        CLUSTER_JSON="{\"name\": \"$${CLUSTER_FQDN}\", \"rack_aware\": true}"
    else
        CLUSTER_JSON="{\"name\": \"$${CLUSTER_FQDN}\"}"
    fi

    # Build JSON payload for cluster creation
    CREATE_PAYLOAD=$(cat <<EOJSON
{
  "action": "create_cluster",
  "cluster": $CLUSTER_JSON,
  "node": {
    "paths": {
%{ if flash_enabled ~}
      "bigstore_path": "/var/opt/redislabs/flash"
%{ else ~}
      "persistent_path": "/var/opt/redislabs/persist"
%{ endif ~}
    },
%{ if flash_enabled ~}
    "bigstore_enabled": true,
%{ endif ~}
    "identity": $IDENTITY_JSON
  },
  "credentials": {
    "username": $ESCAPED_USERNAME,
    "password": $ESCAPED_PASSWORD
  }
}
EOJSON
)

    log "Sending bootstrap request..."
    curl -sk -X POST -H "Content-Type: application/json" -d "$CREATE_PAYLOAD" https://localhost:9443/v1/bootstrap/create_cluster 2>&1 | tee -a "$LOG_FILE" || true

    # Wait for bootstrap to complete
    log "Waiting for cluster creation to complete..."
    BOOTSTRAP_COMPLETED=false
    for i in $(seq 1 60); do
        STATE=$(curl -sk https://localhost:9443/v1/bootstrap 2>/dev/null | jq -r '.bootstrap_status.state // "unknown"' || echo "unknown")
        log "Bootstrap state: $STATE"
        if [ "$STATE" = "completed" ]; then
            log "Cluster creation completed"
            BOOTSTRAP_COMPLETED=true
            break
        fi
        if [ "$STATE" = "error" ]; then
            log "Cluster creation failed!"
            curl -sk https://localhost:9443/v1/bootstrap 2>&1 | tee -a "$LOG_FILE"
            exit 1
        fi
        # Continue polling for unknown/empty/idle states
        sleep 5
    done

    if [ "$BOOTSTRAP_COMPLETED" != "true" ]; then
        log "ERROR: Cluster creation timed out after 5 minutes!"
        curl -sk https://localhost:9443/v1/bootstrap 2>&1 | tee -a "$LOG_FILE"
        exit 1
    fi

    # Apply license if provided
    if [ -n "$${REDIS_LICENSE}" ]; then
        log "Applying Redis Enterprise license..."
        LICENSE_RESPONSE=$(curl -sk -X PUT \
            -u "$${REDIS_ADMIN_USER}:$${REDIS_ADMIN_PASSWORD}" \
            -H "Content-Type: application/json" \
            -d "{\"license\": \"$${REDIS_LICENSE}\"}" \
            https://localhost:9443/v1/license 2>&1)

        # Check if license was applied successfully
        if echo "$LICENSE_RESPONSE" | grep -q '"shards_limit"'; then
            log "License applied successfully"
            log "License details: $LICENSE_RESPONSE"
        else
            log "WARNING: License application may have failed: $LICENSE_RESPONSE"
        fi
    fi
else
    log "Joining cluster at $${MASTER_IP} via REST API"
    max_retries=20
    retry_delay=30

    # Build JSON payload for cluster join
    JOIN_PAYLOAD=$(cat <<EOJSON
{
  "action": "join_cluster",
  "cluster": {
    "nodes": ["$${MASTER_IP}"]
  },
  "node": {
    "paths": {
%{ if flash_enabled ~}
      "bigstore_path": "/var/opt/redislabs/flash"
%{ else ~}
      "persistent_path": "/var/opt/redislabs/persist"
%{ endif ~}
    },
%{ if flash_enabled ~}
    "bigstore_enabled": true,
%{ endif ~}
    "identity": $IDENTITY_JSON
  },
  "credentials": {
    "username": $ESCAPED_USERNAME,
    "password": $ESCAPED_PASSWORD
  }
}
EOJSON
)

    JOIN_COMPLETED=false
    for i in $(seq 1 $max_retries); do
        log "Join attempt $i/$max_retries..."

        # Check if already part of cluster
        STATE=$(curl -sk https://localhost:9443/v1/bootstrap 2>/dev/null | jq -r '.bootstrap_status.state // "idle"' || echo "idle")
        if [ "$STATE" = "completed" ]; then
            log "Already joined cluster"
            JOIN_COMPLETED=true
            break
        fi

        curl -sk -X POST -H "Content-Type: application/json" -d "$JOIN_PAYLOAD" https://localhost:9443/v1/bootstrap/join_cluster 2>&1 | tee -a "$LOG_FILE" || true

        # Wait for join to complete
        for j in $(seq 1 30); do
            STATE=$(curl -sk https://localhost:9443/v1/bootstrap 2>/dev/null | jq -r '.bootstrap_status.state // "unknown"' || echo "unknown")
            if [ "$STATE" = "completed" ]; then
                log "Successfully joined cluster"
                JOIN_COMPLETED=true
                break 2
            fi
            if [ "$STATE" = "error" ]; then
                log "Join failed, will retry..."
                curl -sk https://localhost:9443/v1/bootstrap 2>&1 | tee -a "$LOG_FILE"
                break
            fi
            # Continue polling for unknown/empty/idle states
            sleep 5
        done

        log "Retrying in $${retry_delay}s..."
        sleep $retry_delay
    done

    if [ "$JOIN_COMPLETED" != "true" ]; then
        log "ERROR: Failed to join cluster after $max_retries attempts!"
        curl -sk https://localhost:9443/v1/bootstrap 2>&1 | tee -a "$LOG_FILE"
        exit 1
    fi
fi

# =============================================================================
# Cleanup and Signal Completion
# =============================================================================
rm -f "$${INSTALL_DIR}"/redislabs*.tar

log "=== Redis Enterprise installation complete ==="

# Create marker file to signal cluster is ready
touch /home/$${SSH_USER}/cluster_ready
chown $${SSH_USER}:$${SSH_USER} /home/$${SSH_USER}/cluster_ready

log "Cluster ready marker created"

