#!/bin/bash
# =============================================================================
# Bastion/Client Node Preparation Script
# Generated by terraform-aws-redis-enterprise module
# =============================================================================

set -euo pipefail
exec > >(tee /var/log/bastion-install.log) 2>&1

SSH_USER="${ssh_user}"
CLUSTER_FQDN="${cluster_fqdn}"
MEMTIER_URL="${memtier_url}"
PROMETHEUS_URL="${prometheus_url}"
GRAFANA_VERSION="${grafana_version}"
JAVA_VERSION="${java_version}"

INSTALL_MEMTIER="${install_memtier}"
INSTALL_PROMETHEUS="${install_prometheus}"
INSTALL_GRAFANA="${install_grafana}"
INSTALL_REDISINSIGHT="${install_redisinsight}"
INSTALL_REDIS_CLI="${install_redis_cli}"

LOG_FILE="/home/$${SSH_USER}/prepare_client.log"
INSTALL_DIR="/home/$${SSH_USER}/install"

log() {
    echo "$(date -Is) - $1" | tee -a "$LOG_FILE"
}

# Wait for user home
while [ ! -d "/home/$${SSH_USER}" ]; do
    echo "Waiting for /home/$${SSH_USER}..."
    sleep 5
done

log "=== Starting bastion preparation ==="

# =============================================================================
# Wait for cloud-init
# =============================================================================
log "Waiting for cloud-init..."
cloud-init status --wait || true

while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
    log "Waiting for apt lock..."
    sleep 5
done

# =============================================================================
# APT Configuration
# =============================================================================
export DEBIAN_FRONTEND=noninteractive
export NEEDRESTART_MODE=a

if [ -d /etc/needrestart/conf.d ]; then
    cat > /etc/needrestart/conf.d/99-disable-interactive.conf << 'EOF'
$nrconf{restart} = 'a';
$nrconf{kernelhints} = 0;
EOF
fi

# =============================================================================
# System Packages
# =============================================================================
log "Installing system packages..."
apt-get -y update
apt-get -y install \
    vim htop iputils-ping netcat-openbsd dnsutils curl wget \
    jq openssl ca-certificates python3 python3-pip python3-venv \
    openjdk-$${JAVA_VERSION}-jdk build-essential autoconf automake \
    libpcre3-dev libevent-dev pkg-config zlib1g-dev libssl-dev \
    apt-transport-https software-properties-common gnupg

mkdir -p "$${INSTALL_DIR}"
cd "$${INSTALL_DIR}"

# =============================================================================
# Memtier Benchmark
# =============================================================================
if [ "$${INSTALL_MEMTIER}" = "true" ]; then
    log "Installing memtier_benchmark..."
    wget -O memtier.tar.gz "$${MEMTIER_URL}"
    tar xfz memtier.tar.gz
    mv memtier_benchmark-*/ memtier
    pushd memtier
    autoreconf -ivf
    ./configure
    make -j$(nproc)
    make install
    popd
    log "memtier_benchmark installed"
fi

# =============================================================================
# Redis CLI
# =============================================================================
if [ "$${INSTALL_REDIS_CLI}" = "true" ]; then
    log "Installing redis-cli..."
    curl -fsSL https://packages.redis.io/gpg | gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg
    chmod 644 /usr/share/keyrings/redis-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" > /etc/apt/sources.list.d/redis.list
    apt-get update
    apt-get install -y redis-tools
    systemctl stop redis-server 2>/dev/null || true
    systemctl disable redis-server 2>/dev/null || true
    log "redis-cli installed"
fi

# =============================================================================
# Prometheus
# =============================================================================
if [ "$${INSTALL_PROMETHEUS}" = "true" ]; then
    log "Installing Prometheus..."
    wget -O prometheus.tar.gz "$${PROMETHEUS_URL}"
    tar xfz prometheus.tar.gz
    mv prometheus-*/ prometheus
    
    groupadd --system prometheus 2>/dev/null || true
    useradd -s /sbin/nologin --system -g prometheus prometheus 2>/dev/null || true
    mkdir -p /var/lib/prometheus /etc/prometheus/{rules,rules.d,files_sd}
    
    mv prometheus/prometheus prometheus/promtool /usr/local/bin/
    mv prometheus/consoles/ prometheus/console_libraries/ /etc/prometheus/
    
    cat > /etc/prometheus/prometheus.yml << PROMCFG
global:
  scrape_interval: 15s
rule_files:
  - "rules/*.yml"
scrape_configs:
  - job_name: "redis-enterprise"
    scheme: https
    tls_config:
      insecure_skip_verify: true
    scrape_interval: 30s
    metrics_path: /v2
    static_configs:
      - targets: ['$${CLUSTER_FQDN}:8070']
        labels:
          cluster: '$${CLUSTER_FQDN}'
PROMCFG

    cat > /etc/systemd/system/prometheus.service << 'PROMSVC'
[Unit]
Description=Prometheus
Wants=network-online.target
After=network-online.target

[Service]
User=prometheus
Group=prometheus
ExecStart=/usr/local/bin/prometheus \
  --config.file=/etc/prometheus/prometheus.yml \
  --storage.tsdb.path=/var/lib/prometheus \
  --web.console.templates=/etc/prometheus/consoles \
  --web.console.libraries=/etc/prometheus/console_libraries \
  --web.listen-address=0.0.0.0:9090
Restart=always

[Install]
WantedBy=multi-user.target
PROMSVC

    chown -R prometheus:prometheus /etc/prometheus /var/lib/prometheus
    systemctl daemon-reload
    systemctl enable prometheus
    systemctl start prometheus
    log "Prometheus installed"
fi

# =============================================================================
# Grafana
# =============================================================================
if [ "$${INSTALL_GRAFANA}" = "true" ]; then
    log "Installing Grafana..."
    mkdir -p /etc/apt/keyrings/
    wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor > /etc/apt/keyrings/grafana.gpg
    echo "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main" > /etc/apt/sources.list.d/grafana.list
    apt-get -y update
    apt-get install -y grafana-enterprise=$${GRAFANA_VERSION}

    cat > /etc/grafana/provisioning/datasources/prometheus.yaml << 'GRAFDS'
apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://127.0.0.1:9090
  isDefault: true
GRAFDS

    systemctl enable grafana-server
    systemctl start grafana-server
    log "Grafana installed"
fi

# =============================================================================
# Docker & RedisInsight
# =============================================================================
if [ "$${INSTALL_REDISINSIGHT}" = "true" ]; then
    log "Installing Docker and RedisInsight..."
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" > /etc/apt/sources.list.d/docker.list
    apt-get update
    apt-get -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    usermod -aG docker $${SSH_USER}

    systemctl enable docker
    systemctl start docker
    sleep 5

    docker run -d --name redisinsight --restart unless-stopped \
        -p 0.0.0.0:5540:5540 -v redisinsight:/data redis/redisinsight:latest
    log "RedisInsight container started"
fi

# =============================================================================
# Cleanup and Summary
# =============================================================================
chown -R $${SSH_USER}:$${SSH_USER} "$${INSTALL_DIR}"
chown -R $${SSH_USER}:$${SSH_USER} /home/$${SSH_USER}

log "=== Bastion preparation complete ==="
log "Services:"
log "  - Prometheus: http://localhost:9090"
log "  - Grafana: http://localhost:3000 (admin/admin)"
log "  - RedisInsight: http://localhost:5540"
log "Redis cluster: $${CLUSTER_FQDN}"

touch /home/$${SSH_USER}/bastion_ready
chown $${SSH_USER}:$${SSH_USER} /home/$${SSH_USER}/bastion_ready

